# Configure this as central (right side of split keyboard)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# Specify this is the right side of the split keyboard -> now central
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

# Enable keyboard output from peripheral
CONFIG_ZMK_USB=y
