# Configure this as peripheral (left side of split keyboard)
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y


# This is the central/left side -> now peripheral
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Enable keyboard output from central
CONFIG_ZMK_USB=y

