CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Set sleep timeout to 30min (30*60*1000ms).
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Set custom Bluetooth name
CONFIG_ZMK_KEYBOARD_NAME="Skeletyl"

